# Generated by Django 3.0.7 on 2020-06-20 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_schoolimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SchoolImage',
        ),
    ]
